#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════
#  SupremeAI – ONE-FILE QUICKSTART
#  Run this script once to set up everything and start the app.
#
#  Usage:
#    chmod +x quickstart.sh
#    ./quickstart.sh
#
#  What this does (in order):
#    1. Checks prerequisites (dotnet, az)
#    2. Prompts for your API keys
#    3. Optionally provisions all Azure resources (Key Vault, OpenAI, AI Foundry)
#    4. Writes your keys to a local .env file for the API
#    5. Starts the backend API  (http://localhost:5100)
#    6. Starts the Blazor frontend (http://localhost:5095)
# ═══════════════════════════════════════════════════════════════════════
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
API_DIR="$REPO_ROOT/src/SupremeAI.Api"
UI_DIR="$REPO_ROOT/src"
ENV_FILE="$API_DIR/.env"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC} $*"; }
prompt()  { echo -e "${CYAN}[INPUT]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
header()  { echo -e "\n${BOLD}${CYAN}══ $* ══${NC}"; }

# ─────────────────────────────────────────────────────────────────────
# STEP 1 – Prerequisites
# ─────────────────────────────────────────────────────────────────────
header "Step 1 – Checking prerequisites"

if ! command -v dotnet &>/dev/null; then
  echo -e "${RED}[ERROR]${NC} .NET SDK not found."
  echo "  Install from: https://dotnet.microsoft.com/download"
  exit 1
fi
info ".NET SDK: $(dotnet --version)"

AZURE_CLI_AVAILABLE=false
if command -v az &>/dev/null; then
  AZURE_CLI_AVAILABLE=true
  info "Azure CLI: $(az version --query '"azure-cli"' -o tsv 2>/dev/null)"
else
  warn "Azure CLI not found – Azure provisioning will be skipped."
  warn "Install from: https://aka.ms/installazurecliwindows or via brew/apt"
fi

# ─────────────────────────────────────────────────────────────────────
# STEP 2 – Collect API keys
# ─────────────────────────────────────────────────────────────────────
header "Step 2 – API Keys"
echo ""
echo "  Enter your API keys below. Press ENTER to skip any key you don't have yet."
echo "  (Models without keys will return a friendly error but won't crash the app.)"
echo ""

# Load existing .env so users don't have to re-enter keys on re-runs
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE" 2>/dev/null || true
  info "Loaded existing keys from $ENV_FILE"
fi

read_key() {
  local var_name="$1"
  local label="$2"
  local current_val="${!var_name:-}"
  if [[ -n "$current_val" ]]; then
    prompt "$label [already set – press ENTER to keep]: "
  else
    prompt "$label (press ENTER to skip): "
  fi
  read -r input
  if [[ -n "$input" ]]; then
    eval "$var_name='$input'"
  fi
}

read_key AZURE_OPENAI_ENDPOINT   "Azure OpenAI Endpoint (e.g. https://myoai.openai.azure.com/)"
read_key AZURE_OPENAI_API_KEY    "Azure OpenAI API Key"
read_key ANTHROPIC_API_KEY        "Anthropic API Key (for Claude 3.5 Sonnet)"
read_key GOOGLE_GEMINI_API_KEY    "Google Gemini API Key (for Gemini 1.5 Pro)"
read_key XAI_GROK_API_KEY         "xAI Grok API Key (for Grok-2)"

# Azure AI Inference keys (set by Azure setup; can also be entered manually)
read_key PHI_35_MINI_ENDPOINT    "Azure AI – Phi-3.5 Mini endpoint URL"
read_key PHI_35_MINI_API_KEY     "Azure AI – Phi-3.5 Mini API key"
read_key PHI_3_MEDIUM_ENDPOINT   "Azure AI – Phi-3 Medium endpoint URL"
read_key PHI_3_MEDIUM_API_KEY    "Azure AI – Phi-3 Medium API key"
read_key LLAMA_31_70B_ENDPOINT   "Azure AI – Llama 3.1 70B endpoint URL"
read_key LLAMA_31_70B_API_KEY    "Azure AI – Llama 3.1 70B API key"
read_key MISTRAL_LARGE_ENDPOINT  "Azure AI – Mistral Large endpoint URL"
read_key MISTRAL_LARGE_API_KEY   "Azure AI – Mistral Large API key"
read_key COMMAND_R_PLUS_ENDPOINT "Azure AI – Command R+ endpoint URL"
read_key COMMAND_R_PLUS_API_KEY  "Azure AI – Command R+ API key"
read_key JAIS_30B_ENDPOINT       "Azure AI – Jais 30B endpoint URL"
read_key JAIS_30B_API_KEY        "Azure AI – Jais 30B API key"

# Write .env file
cat > "$ENV_FILE" <<EOF
# SupremeAI API – environment variables
# Generated by quickstart.sh on $(date)
AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY:-}
XAI_GROK_API_KEY=${XAI_GROK_API_KEY:-}
PHI_35_MINI_ENDPOINT=${PHI_35_MINI_ENDPOINT:-}
PHI_35_MINI_API_KEY=${PHI_35_MINI_API_KEY:-}
PHI_3_MEDIUM_ENDPOINT=${PHI_3_MEDIUM_ENDPOINT:-}
PHI_3_MEDIUM_API_KEY=${PHI_3_MEDIUM_API_KEY:-}
LLAMA_31_70B_ENDPOINT=${LLAMA_31_70B_ENDPOINT:-}
LLAMA_31_70B_API_KEY=${LLAMA_31_70B_API_KEY:-}
MISTRAL_LARGE_ENDPOINT=${MISTRAL_LARGE_ENDPOINT:-}
MISTRAL_LARGE_API_KEY=${MISTRAL_LARGE_API_KEY:-}
COMMAND_R_PLUS_ENDPOINT=${COMMAND_R_PLUS_ENDPOINT:-}
COMMAND_R_PLUS_API_KEY=${COMMAND_R_PLUS_API_KEY:-}
JAIS_30B_ENDPOINT=${JAIS_30B_ENDPOINT:-}
JAIS_30B_API_KEY=${JAIS_30B_API_KEY:-}
EOF

info "Keys saved to $ENV_FILE"

# ─────────────────────────────────────────────────────────────────────
# STEP 3 – Optional: Provision Azure resources
# ─────────────────────────────────────────────────────────────────────
header "Step 3 – Azure Resource Provisioning (optional)"

if [[ "$AZURE_CLI_AVAILABLE" == "true" ]]; then
  echo ""
  prompt "Do you want to provision Azure resources now? (Azure OpenAI, AI Foundry, Key Vault)"
  prompt "This takes 10-20 min and requires an Azure subscription. [y/N]: "
  read -r do_azure
  if [[ "${do_azure,,}" == "y" ]]; then
    info "Running Azure setup…"
    bash "$REPO_ROOT/scripts/azure/setup.sh"

    # After Azure setup, read endpoint + key back from Key Vault
    KV_NAME=$(az keyvault list -g supremeai-rg --query "[0].name" -o tsv 2>/dev/null || true)
    if [[ -n "$KV_NAME" ]]; then
      info "Reading Azure OpenAI endpoint and key from Key Vault '$KV_NAME'…"
      AZURE_OPENAI_ENDPOINT=$(az keyvault secret show --vault-name "$KV_NAME" --name azure-openai-endpoint --query value -o tsv 2>/dev/null || echo "")
      AZURE_OPENAI_API_KEY=$(az keyvault secret show  --vault-name "$KV_NAME" --name azure-openai-api-key  --query value -o tsv 2>/dev/null || echo "")

      # Update .env with the retrieved values
      sed -i "s|AZURE_OPENAI_ENDPOINT=.*|AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}|" "$ENV_FILE"
      sed -i "s|AZURE_OPENAI_API_KEY=.*|AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}|"   "$ENV_FILE"
      info "Updated .env with Azure OpenAI credentials."
    fi
  else
    info "Skipping Azure provisioning."
  fi
else
  warn "Azure CLI not available – skipping Azure provisioning."
fi

# ─────────────────────────────────────────────────────────────────────
# STEP 4 – Build projects
# ─────────────────────────────────────────────────────────────────────
header "Step 4 – Building projects"

info "Restoring & building backend API…"
cd "$API_DIR" && dotnet build -c Release --nologo -q
info "Backend API built."

info "Restoring & building Blazor frontend…"
cd "$UI_DIR" && dotnet build -c Release --nologo -q
info "Frontend built."

# ─────────────────────────────────────────────────────────────────────
# STEP 5 – Start the backend API
# ─────────────────────────────────────────────────────────────────────
header "Step 5 – Starting backend API on http://localhost:5100"

# Load .env into the environment for the API process
set -a
# shellcheck disable=SC1090
source "$ENV_FILE" 2>/dev/null || true
set +a

cd "$API_DIR"
dotnet run --project . --no-build --urls "http://localhost:5100" &
API_PID=$!
info "Backend API started (PID $API_PID)"

# Wait for API to be ready
echo -n "  Waiting for API to be ready"
for i in {1..30}; do
  if curl -sf "http://localhost:5100/api/ai/models" &>/dev/null; then
    echo " ✓"
    break
  fi
  echo -n "."
  sleep 1
done

# ─────────────────────────────────────────────────────────────────────
# STEP 6 – Start the Blazor frontend
# ─────────────────────────────────────────────────────────────────────
header "Step 6 – Starting Blazor frontend on http://localhost:5095"

cd "$UI_DIR"
dotnet run --project . --no-build &
UI_PID=$!
info "Frontend started (PID $UI_PID)"

# ─────────────────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║            SupremeAI is running! 🚀                  ║${NC}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Frontend${NC}: http://localhost:5095"
echo -e "  ${BOLD}Backend API${NC}: http://localhost:5100"
echo -e "  ${BOLD}API Docs (Swagger)${NC}: http://localhost:5100/swagger"
echo ""
echo "  Press Ctrl+C to stop both servers."
echo ""

# Wait for Ctrl+C and clean up both processes
trap 'echo ""; info "Shutting down..."; kill $API_PID $UI_PID 2>/dev/null; exit 0' SIGINT SIGTERM
wait
